from typing import Any

from pydantic import BaseModel


class QueryResponse(BaseModel):
    """
    Standard response returned by the InsightIQ API.
    """

    # Whether the request succeeded
    success: bool

    # General status message
    message: str

    # Original user question
    question: str

    # SQL generated by Gemini and executed on BigQuery
    

    # Business-friendly explanation generated by Gemini
    answer: str

    # Number of rows returned
    row_count: int

    # Raw query results from BigQuery
    data: list[dict[str, Any]]